services:
  express-db:
    image: postgres:17
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cesare
      POSTGRES_DB: tutoriales
    ports:
      - 5432:5432
